caption: Settings for Generative AI Wallpaper feature
desc: |-
  This policy enables or disables Generative AI Wallpaper feature for <ph name="PRODUCT_OS_NAME">$1<ex>Google ChromeOS</ex></ph>.
  1 is the default value.

  1 = Allow Generative AI Wallpaper without improving AI models. 1 is the default value for Enterprise users managed by <ph name="GOOGLE_ADMIN_CONSOLE_PRODUCT_NAME">Google Admin console</ph> and Education accounts managed by <ph name="GOOGLE_WORKSPACE_PRODUCT_NAME">Google Workspace</ph>.

  2 = Do not allow Generative AI Wallpaper.

  For more information on data handling for generative AI features, please see https://support.google.com/chrome/a?p=generative_ai_settings.
default: 1
example_value: 2
features:
  dynamic_refresh: true
  per_profile: true
owners:
- file://ash/webui/personalization_app/OWNERS
items:
- caption: Allow Generative AI Wallpaper without improving AI models
  name: AllowedWithoutLogging
  value: 1
- caption: Do not allow Generative AI Wallpaper
  name: Disabled
  value: 2
schema:
  enum:
  - 1
  - 2
  type: integer
future_on:
- chrome_os
tags: []
type: int-enum