// Copyright (c) 2015 Vivaldi Technologies AS. All rights reserved

#ifndef NOTIFICATIONS_VIVALDI_WEB_VIEW_PERMISSION_TYPES_H_
#define NOTIFICATIONS_VIVALDI_WEB_VIEW_PERMISSION_TYPES_H_

    // NOTE: Included verbatim in chromium/extensions/browser/guest_view/web_view/web_view_permission_types.h
    WEB_VIEW_PERMISSION_TYPE_NOTIFICATION,

#endif  // NOTIFICATIONS_VIVALDI_WEB_VIEW_PERMISSION_TYPES_H_
