// Copyright (c) 2015 Vivaldi Technologies AS. All rights reserved

#ifndef EXTENSIONS_PERMISSIONS_VIVALDI_API_PERMISSION_ENUMS_H_
#define EXTENSIONS_PERMISSIONS_VIVALDI_API_PERMISSION_ENUMS_H_

    // vivaldi permissions

    // NOTE: Included verbatim in chromium/extensions/common/permissions/api_permission.h

    // remember to add new permissions to PermissionsTest.PermissionMessages in
    // chrome/common/extensions/permissions/permission_set_unittest.cc
    kAutoUpdate,
    kBookmarksPrivate,
    kCalendar,
    kContacts,
    kDevtoolsPrivate,
    kExtensionActionUtils,
    kHistoryPrivate,
    kImportData,
    kInfobars,
    kEditCommand,
    kMailPrivate,
    kZoom,
    kNotes,
    kPrefs,
    kRuntimePrivate,
    kSavedPasswords,
    kSessionsPrivate,
    kSettings,
    kShowMenu,
    kSync,
    kTabsPrivate,
    kThumbnails,
    kUtilities,
    kWebViewPrivate,
    kWindowPrivate,

#endif  // EXTENSIONS_PERMISSIONS_VIVALDI_API_PERMISSION_ENUMS_H_
