// Copyright 2023 Vivaldi Technologies. All rights reserved.

#ifndef IOS_CHROME_BROWSER_UI_TAB_SWITCHER_TAB_GRID_VIVALDI_TAB_GRID_EMPTY_STATE_VIEW_DELEGATE_H_
#define IOS_CHROME_BROWSER_UI_TAB_SWITCHER_TAB_GRID_VIVALDI_TAB_GRID_EMPTY_STATE_VIEW_DELEGATE_H_

@protocol VivaldiTabGridEmptyStateViewDelegate<NSObject>

- (void)didSelectLoginFromEmptyStateView;
- (void)didSelectRegisterFromEmptyStateView;
- (void)didSelectEnableSyncFromEmptyStateView;

@end

#endif  // IOS_CHROME_BROWSER_UI_TAB_SWITCHER_TAB_GRID_VIVALDI_TAB_GRID_EMPTY_STATE_VIEW_DELEGATE_H_
