// Copyright (c) 2015 Vivaldi Technologies AS. All rights reserved
#include "testing/disable_unittests_macros.h"

// List of unittest disabled for Linux by Vivaldi
// On the form
//    DISABLE(foo,bar)
//    DISABLE(foo,baz)

    DISABLE(AudioFileReaderTest, AAC)
    DISABLE(AudioFileReaderTest, CorruptMP3)
    DISABLE(AudioFileReaderTest, MP3)
    DISABLE_MULTI(AudioDecoderTest, Decode)
    DISABLE_MULTI(AudioDecoderTest, Initialize)
    DISABLE_MULTI(AudioDecoderTest, NoTimestamp)
    DISABLE_MULTI(AudioDecoderTest, ProduceAudioSamples)
    DISABLE_MULTI(AudioDecoderTest, Reset)
    DISABLE(FFmpegDemuxerTest, HEVC_in_MP4_container)
    DISABLE(FFmpegDemuxerTest, IsValidAnnexB)
    DISABLE(FFmpegDemuxerTest, Mp3WithVideoStreamID3TagData)
    DISABLE(FFmpegDemuxerTest, NaturalSizeWithPASP)
    DISABLE(FFmpegDemuxerTest, NaturalSizeWithoutPASP)
    DISABLE(FFmpegDemuxerTest, Read_AC3_Audio)
    DISABLE(FFmpegDemuxerTest, Read_EAC3_Audio)
    DISABLE(FFmpegDemuxerTest, Rotate_Metadata_0)
    DISABLE(FFmpegDemuxerTest, Rotate_Metadata_180)
    DISABLE(FFmpegDemuxerTest, Rotate_Metadata_270)
    DISABLE(FFmpegDemuxerTest, Rotate_Metadata_90)
    DISABLE(MediaFileCheckerTest, MP3)
    DISABLE_MULTI(Mp3SeekFFmpegDemuxerTest, TestFastSeek)
    DISABLE(AudioFileReaderTest, MidStreamConfigChangesFail)
    DISABLE(FFmpegDemuxerTest, MP4_ZeroStszEntry)
    DISABLE(FFmpegDemuxerTest, NoID3TagData)
    DISABLE(EncryptedMediaSupportedTypesClearKeyTest, Audio_MP4)
    DISABLE(EncryptedMediaSupportedTypesClearKeyTest, Video_MP4)
    DISABLE(EncryptedMediaSupportedTypesExternalClearKeyTest, Audio_MP4)
    DISABLE(EncryptedMediaSupportedTypesExternalClearKeyTest, Video_MP4)
    DISABLE(EncryptedMediaSupportedTypesWidevineTest, Audio_MP4)
    DISABLE(EncryptedMediaSupportedTypesWidevineTest, Video_MP4)
    DISABLE(MediaCanPlayTypeTest, CodecSupportTest_mp4)

    DISABLE_MULTI(QuicClientSessionTest, SetFecProtectionFromConfig)
