// Copyright 2023 Vivaldi Technologies. All rights reserved.

#ifndef IOS_UI_SETTINGS_SYNC_MANAGER_VIVALDI_SYNC_SIMPLIFIED_STATE_H_
#define IOS_UI_SETTINGS_SYNC_MANAGER_VIVALDI_SYNC_SIMPLIFIED_STATE_H_

// Enum for the vivaldi sync simplified states.
typedef NS_ENUM(NSUInteger, VivaldiSyncSimplifiedState) {
  SYNC_STATE_FAILED = 0,
  SYNC_STATE_CLEARING_DATA,
  SYNC_STATE_CONFIG_PENDING,
  SYNC_STATE_STARTED_SUCCESS,
  SYNC_STATE_STARTED_ERROR,
  SYNC_STATE_STARTING_SERVER_ERROR,
  SYNC_STATE_STARTING,
  SYNC_STATE_STOPPED,
  SYNC_STATE_DEFAULT
};

#endif  // IOS_UI_SETTINGS_SYNC_MANAGER_VIVALDI_SYNC_SIMPLIFIED_STATE_H_
