// Copyright (c) 2016 Vivaldi. All rights reserved.

#ifndef BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
#define BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_

#define IDC_VIVALDI_MENU_ENUMS_START 56000
#define IDC_VIV_CONTENT_CONTEXT_ADDSEARCHENGINE 56000
#define IDC_VIV_RELOAD_IMAGE 56001
#define IDC_VIV_OPEN_LINK_BACKGROUND_TAB 56002
#define IDC_VIV_BOOKMARK_BAR_NEW_SEPARATOR 56003
#define IDC_VIV_CONTENT_INSERT_NOTE 56004
#define IDC_VIV_OPEN_IMAGE_NEW_FOREGROUND_TAB 56005
#define IDC_VIV_OPEN_IMAGE_NEW_BACKGROUND_TAB 56006
#define IDC_VIV_OPEN_IMAGE_NEW_WINDOW 56007
#define IDC_VIV_OPEN_IMAGE_NEW_PRIVATE_WINDOW 56008
#define IDC_VIV_COPY_TO_NOTE 56009
#define IDC_VIV_BOOKMARK_PAGE 56010
#define IDC_VIV_BOOKMARK_LINK 56011
#define IDC_VIV_ADD_PAGE_TO_WEBPANEL 56012
#define IDC_VIV_ADD_LINK_TO_WEBPANEL 56013
#define IDC_VIV_COPY_PAGE_ADDRESS 56014
#define IDC_VIV_USE_IMAGE_AS_BACKGROUND 56015
#define IDC_VIV_FULLSCREEN 56016
#define IDC_VIV_VALIDATE_PAGE 56017
#define IDC_VIV_OPEN_LINK_CURRENT_TAB 56018
#define IDC_VIV_SEND_LINK_BY_MAIL 56019
#define IDC_VIV_SEND_PAGE_BY_MAIL 56020
#define IDC_VIV_SEND_SELECTION_BY_MAIL 56021
#define IDC_VIV_OPEN_IMAGE_CURRENT_TAB 56022
#define IDC_VIV_INSPECT_IMAGE 56023
#define IDC_VIV_BOOKMARK_BAR_OPEN_CURRENT_TAB 56024
#define IDC_VIV_BOOKMARK_BAR_OPEN_NEW_TAB 56025
#define IDC_VIV_BOOKMARK_BAR_OPEN_BACKGROUND_TAB 56026
#define IDC_VIV_BOOKMARK_BAR_OPEN_NEW_WINDOW 56027
#define IDC_VIV_BOOKMARK_BAR_OPEN_NEW_PRIVATE_WINDOW 56028
#define IDC_VIV_BOOKMARK_BAR_ADD_ACTIVE_TAB 56029
#define IDC_VIV_ADD_AS_EVENT 56030
#define IDC_VIV_INSPECT_SERVICE_WORKER 56031
#define IDC_VIV_INSPECT_PORTAL_DOCUMENT 56032
// These two define a range
#define IDC_VIV_OPEN_IMAGE_IN_PROFILE_FIRST 56050
#define IDC_VIV_OPEN_IMAGE_IN_PROFILE_LAST 56100
// These two define a range
#define IDC_VIV_SEND_TO_DEVICE_FIRST 56101
#define IDC_VIV_SEND_TO_DEVICE_LAST 56150

// Menu ids starts from this base. Some may be overriden by those above.
// For clarity: Items in a menu spec from JS have ids starting from 0. An id
// number is added to IDC_VIV_MENU_FIRST when we prepare the menu.
// IDC_VIV_MENU_FIRST is picked so that it (and all the way up to
// IDC_VIVALDI_MENU_ENUMS_END) will not conflict with hardcoded chromium ids.
// When a menu action is executed - and if action is to be handled in JS - the
// id will be subtracted by IDC_VIV_MENU_FIRST before notifying JS.
#define IDC_VIV_MENU_FIRST 56160

#define IDC_VIVALDI_MENU_ENUMS_END 57000

#endif  // BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
