// Copyright (c) 2016 Vivaldi. All rights reserved.

#ifndef BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
#define BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_

#define IDC_VIVALDI_MENU_ENUMS_START 56000
#define IDC_VIV_CONTENT_CONTEXT_ADDSEARCHENGINE 56000
#define IDC_CONTENT_CONTEXT_RELOADIMAGE 56001
#define IDC_CONTENT_CONTEXT_OPENLINKBACKGROUNDTAB 56002
#define IDC_CONTENT_CONTEXT_PASTE_AND_GO 56003
#define IDC_VIV_CONTENT_INSERT_NOTE  56004
#define IDC_VIV_OPEN_IMAGE_NEW_FOREGROUND_TAB 56005
#define IDC_VIV_OPEN_IMAGE_NEW_BACKGROUND_TAB 56006
#define IDC_VIV_OPEN_IMAGE_NEW_WINDOW 56007
#define IDC_VIV_OPEN_IMAGE_NEW_PRIVATE_WINDOW 56008
#define IDC_VIVALDI_MENU_ENUMS_END 57000

#endif  // BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
