// Copyright (c) 2016 Vivaldi. All rights reserved.

#ifndef BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
#define BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_

#define IDC_VIVALDI_MENU_ENUMS_START 56000
#define IDC_VIV_CONTENT_CONTEXT_ADDSEARCHENGINE 56000
#define IDC_CONTENT_CONTEXT_RELOADIMAGE 56001
#define IDC_CONTENT_CONTEXT_OPENLINKBACKGROUNDTAB 56002
#define IDC_CONTENT_CONTEXT_PASTE_AND_GO 56003

#define IDC_VIVALDI_MENU_ENUMS_END 57000

#endif  // BROWSER_MENUS_VIVALDI_MENU_ENUMS_H_
