
// included by "extensions/browser/guest_view/web_view/web_view_guest.h"

#include "ui/base/ui_base_types.h"
#include "components/content_settings/core/common/content_settings_types.h"

namespace extensions {
class DevtoolsConnectorItem;
}

namespace aura {
namespace client {
class CursorClient;
}
}

namespace blink {
namespace mojom {
class WindowFeatures;
}  // namespace mojom
}  // namespace blink
