
// included by "extensions/browser/guest_view/web_view/web_view_guest.h"
// constructor

// WebViewGuest::WebViewGuest(...) :
// other variables
      has_left_mousebutton_down_(false),
      has_right_mousebutton_down_(false),
      eat_next_right_mouseup_(false),
      current_host_(NULL),
      is_visible_(false),
      is_fullscreen_(false),
      window_state_prior_to_fullscreen_(ui::SHOW_STATE_NORMAL),

//    weak_ptr_factory_(this)
